In [1]:
import numpy as np

In [2]:
simple_list = [1,2,3]
np.array(simple_list)

array([1, 2, 3])

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [5]:
np.zeros(20)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [6]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [8]:
np.zeros((5,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [9]:
np.ones((5,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [12]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [13]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [16]:
np.eye(5,2)

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [18]:
np.random.rand(8,9)

array([[ 0.89181664,  0.81944786,  0.50320839,  0.4212917 ,  0.03219144,
         0.86137948,  0.52916551,  0.23439022,  0.1929684 ],
       [ 0.86749488,  0.15288468,  0.52025289,  0.19263474,  0.54656947,
         0.1836251 ,  0.72333753,  0.54952116,  0.93196288],
       [ 0.28628006,  0.34708387,  0.62872234,  0.50192911,  0.748529  ,
         0.21059362,  0.34387643,  0.416286  ,  0.54857259],
       [ 0.94533537,  0.92469904,  0.28767841,  0.86936221,  0.1370705 ,
         0.71834698,  0.09320322,  0.42055124,  0.36146833],
       [ 0.80839233,  0.60722071,  0.64689044,  0.84648162,  0.4217583 ,
         0.09776054,  0.32999191,  0.6095034 ,  0.56578755],
       [ 0.11207429,  0.04016833,  0.24826384,  0.10096426,  0.42425107,
         0.69868209,  0.99227038,  0.69591822,  0.92076771],
       [ 0.67768066,  0.47771301,  0.90637071,  0.53014064,  0.17886885,
         0.44855642,  0.1055123 ,  0.69797309,  0.6824758 ],
       [ 0.60757718,  0.84296771,  0.53190355,  0.61888123,  0

In [19]:
np.random.randn(8,9)

array([[-0.38594208,  0.94338483,  0.85695884, -0.9470291 , -0.30016577,
        -1.63042838, -1.58195275,  0.65596519, -0.31954639],
       [-0.22296649, -0.41264075,  1.34592402, -1.75637229, -1.40220171,
        -0.16402046, -0.37182531,  0.74796629,  1.50897923],
       [-0.21000271,  1.1261548 ,  0.6065199 ,  0.86830659,  0.17797073,
        -1.03375473, -1.27190472, -0.96938164,  0.19268256],
       [ 0.58595512, -1.30886656,  1.98581949,  0.85186323,  0.04775398,
         0.00355154,  1.52068223,  0.483599  ,  0.13820514],
       [ 0.83569181,  1.30673159, -0.56812767, -1.06186397,  1.53819256,
         0.46398638, -1.34913415,  0.75216329, -0.95523666],
       [-1.40183915, -0.78604207,  0.80576228, -0.24206565,  2.45829277,
         1.08633488, -0.33813908,  0.10009785,  0.4957156 ],
       [ 1.23439077,  0.78895366, -0.1379092 , -0.89737569,  1.8477998 ,
         0.3438773 , -0.10761368,  0.25998021, -0.90978376],
       [ 1.56246806, -0.9948757 ,  0.32419671, -0.98996596, -0

In [20]:
np.random.randint(5,20)

18

In [21]:
np.random.randint(5,20,10)

array([19, 16, 13, 17, 16,  6, 17,  8, 10,  6])

In [38]:
sample_array = np.random.randint(5,70,30)
sample_array

array([ 6, 43,  6, 40,  7,  9, 35, 38, 22, 50, 57, 43, 16, 19, 65, 30,  8,
       64, 31, 54, 44, 23, 26, 68, 30, 16, 15, 21, 57,  5])

In [39]:
sample_array.reshape(5,6)

array([[ 6, 43,  6, 40,  7,  9],
       [35, 38, 22, 50, 57, 43],
       [16, 19, 65, 30,  8, 64],
       [31, 54, 44, 23, 26, 68],
       [30, 16, 15, 21, 57,  5]])

In [40]:
sample_array.max()

68

In [41]:
sample_array.min()

5

In [42]:
sample_array.argmax()

23

In [43]:
sample_array.argmin()

29

In [44]:
sample_array.dtype

dtype('int32')

In [45]:
sample_array.reshape(5,6)

array([[ 6, 43,  6, 40,  7,  9],
       [35, 38, 22, 50, 57, 43],
       [16, 19, 65, 30,  8, 64],
       [31, 54, 44, 23, 26, 68],
       [30, 16, 15, 21, 57,  5]])

In [46]:
sample_array.reshape(5,6).T

array([[ 6, 35, 16, 31, 30],
       [43, 38, 19, 54, 16],
       [ 6, 22, 65, 44, 15],
       [40, 50, 30, 23, 21],
       [ 7, 57,  8, 26, 57],
       [ 9, 43, 64, 68,  5]])

In [49]:
sample_array1 = np.arange(10,21)
sample_array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
sample_array1[8]

18

In [50]:
sample_array1[2:5]

array([12, 13, 14])

In [52]:
sample_array1[[2,5]]

array([12, 15])

In [53]:
sample_array1[2:5]=1000

In [54]:
sample_array1

array([  10,   11, 1000, 1000, 1000,   15,   16,   17,   18,   19,   20])

In [59]:
sample_array1_copy = sample_array1.copy()

In [60]:
sample_array1_copy[:]=1000

In [61]:
sample_array1_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [62]:
sample_array1

array([  10,   11, 1000, 1000, 1000,   15,   16,   17,   18,   19,   20])

In [63]:
np.sqrt(sample_array1)

array([  3.16227766,   3.31662479,  31.6227766 ,  31.6227766 ,
        31.6227766 ,   3.87298335,   4.        ,   4.12310563,
         4.24264069,   4.35889894,   4.47213595])

In [64]:
np.log(sample_array1)

array([ 2.30258509,  2.39789527,  6.90775528,  6.90775528,  6.90775528,
        2.7080502 ,  2.77258872,  2.83321334,  2.89037176,  2.94443898,
        2.99573227])

In [65]:
np.save("file_name",np.log(sample_array1))

In [66]:
np.savez("file_name.npz",a=sample_array1,b=sample_array1_copy)

In [67]:
archive = np.load("file_name.npz")

In [68]:
archive["a"]

array([  10,   11, 1000, 1000, 1000,   15,   16,   17,   18,   19,   20])

In [69]:
archive["b"]

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [71]:
np.savetxt("array_text.txt",sample_array1,delimiter=',')
np.loadtxt("array_text.txt")

array([   10.,    11.,  1000.,  1000.,  1000.,    15.,    16.,    17.,
          18.,    19.,    20.])