# NumPy Lab Exercises 

Solve the following questions in Lab to test your knowledge on NumPy Package!

#### Import NumPy package as np

In [2]:
import numpy as np

#### Create an array of 20 0's 

In [2]:
np.zeros(20)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an array of 20 1's

In [3]:
np.ones(20)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array containing 30 sixes

In [4]:
np.ones(30) *  6

array([ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  6.,  6.,  6.])

#### Create an array of integers starting from 21 until 31

In [5]:
np.arange(21,32)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

#### Create an array of all even integers from 2 to 60

In [6]:
np.arange(2,61,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

#### Create a 5x6 matrix with values ranging from 0 to 29

In [9]:
matrix_data = np.arange(0,30)
matrix_data.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### Create an identity matrix of shape 5x5

In [10]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

In [15]:
np.random.rand(10)

array([ 0.50878552,  0.02532558,  0.47916958,  0.83891456,  0.22226286,
        0.05531868,  0.52860407,  0.83165649,  0.29789442,  0.19146706])

#### Use NumPy to generate an array of 15 random numbers sampled from a standard normal distribution

In [16]:
np.random.randn(15)

array([ 1.1981974 ,  2.10197236,  0.22296764, -0.60475696,  0.16575271,
        0.0611815 ,  0.37245765, -0.25627139,  0.48212443, -0.97435907,
       -0.80733901, -1.53038293,  0.43296283, -0.30458228,  0.72685093])

#### Create the following 5x10 matrix with the values using arange,reshape and arithmetic operators:

In [21]:
np.arange(1,51).reshape(5,10)*0.01

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ]])

#### Create an array of 30 linearly spaced points between 0 and 10:

In [23]:
np.linspace(0,10,num=30)

array([  0.        ,   0.34482759,   0.68965517,   1.03448276,
         1.37931034,   1.72413793,   2.06896552,   2.4137931 ,
         2.75862069,   3.10344828,   3.44827586,   3.79310345,
         4.13793103,   4.48275862,   4.82758621,   5.17241379,
         5.51724138,   5.86206897,   6.20689655,   6.55172414,
         6.89655172,   7.24137931,   7.5862069 ,   7.93103448,
         8.27586207,   8.62068966,   8.96551724,   9.31034483,
         9.65517241,  10.        ])

## Numpy Indexing and Selections

Using the below given Matrix, generate the output for the below questions

In [50]:
simple_matrix = np.arange(1,101).reshape(10,10)
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [44]:
simple_matrix[[-2,-1],:3]

array([[81, 82, 83],
       [91, 92, 93]])

#### Retrieve the value 55 from the above matrix using index & selection technique

In [35]:
simple_matrix[5,4]

55

#### Retrieve the values from the 3rd column in the above matrix

In [39]:
simple_matrix[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

#### Retrieve the values from the 4th row in the above matrix

In [40]:
simple_matrix[3,:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

#### Retrieve values from the 2nd & 4th rows in the above matrix

In [41]:
simple_matrix[[1,4],:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

### Calculate the following values for the given matrix

#### Calculate sum of all the values in the matrix

In [45]:
simple_matrix.sum()

5050

#### Calculate standard deviation of all the values in the matrix

In [46]:
simple_matrix.std()

28.866070047722118

#### Calculate the variance of all values in the matrix

In [47]:
simple_matrix.var()

833.25

#### Calculate the mean of all values in the matrix

In [48]:
simple_matrix.mean()

50.5

#### Largest and smallest number from matrix

In [51]:
simple_matrix.max()

100

In [52]:
simple_matrix.min()

1

#### Create an empty array of 20 0's and replace the 4th object with the number 5

In [8]:
array = np.zeros(20)
array[3]=5
array

array([ 0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an empty array of 20 1's and store it in the variable named array_master. copy the same array to another variable named array_copy

In [10]:
array_master = np.ones(20)
array_copy = array_master.copy()


#### Create an empty array of 30 1's and broadcast all the one's to the value 100

In [12]:
array = np.ones(30)
array[:]=100
array

array([ 100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,
        100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,
        100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,
        100.,  100.,  100.])

#### Create an array of integers starting from 21 until 31 and name it as array1
#### Create an array of integers starting from 11 until 21 and name it as array2

#### Calculate the difference between array1 and array2

In [14]:
array1 = np.arange(21,32)
array2 = np.arange(11,22)

array1 - array2 

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

#### Create an array of all even integers from 2 to 10 and name it as a1
#### Create an array of all even integers from 22 to 30 and name it as a2

#### a. Use the 2 arrays as rows and create a matrix 

In [25]:
a1 = np.arange(2,11,2)
a2 = np.arange(22,31,2)
np.stack((a1,a2))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

#### Use the 2 arrays as columns and create a matrix

In [23]:
np.column_stack((a1,a2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

#### Create a 5x6 matrix with values ranging from 0 to 29 and retrive the value intersecting at 2nd row and 3rd coulumn

In [30]:
array=np.arange(30)
array.reshape(5,6)[1][2]

8

#### Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [37]:
a = np.eye(10)
a[a == 0] = 21
a

array([[  1.,  21.,  21.,  21.,  21.,  21.,  21.,  21.,  21.,  21.],
       [ 21.,   1.,  21.,  21.,  21.,  21.,  21.,  21.,  21.,  21.],
       [ 21.,  21.,   1.,  21.,  21.,  21.,  21.,  21.,  21.,  21.],
       [ 21.,  21.,  21.,   1.,  21.,  21.,  21.,  21.,  21.,  21.],
       [ 21.,  21.,  21.,  21.,   1.,  21.,  21.,  21.,  21.,  21.],
       [ 21.,  21.,  21.,  21.,  21.,   1.,  21.,  21.,  21.,  21.],
       [ 21.,  21.,  21.,  21.,  21.,  21.,   1.,  21.,  21.,  21.],
       [ 21.,  21.,  21.,  21.,  21.,  21.,  21.,   1.,  21.,  21.],
       [ 21.,  21.,  21.,  21.,  21.,  21.,  21.,  21.,   1.,  21.],
       [ 21.,  21.,  21.,  21.,  21.,  21.,  21.,  21.,  21.,   1.]])

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

#### Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [48]:
np.random.seed(10)
a = np.random.rand(10)
print(a)
a > 0.2

[ 0.77132064  0.02075195  0.63364823  0.74880388  0.49850701  0.22479665
  0.19806286  0.76053071  0.16911084  0.08833981]


array([ True, False,  True,  True,  True,  True, False,  True, False, False], dtype=bool)

### End of Lab Exercise - NumPy